language: python
before_install:
- pip install pycodestyle
- pip install pytest
- pip install pytest-cov
- pip install coveralls
- pip install sphinx
- pip install sphinx_rtd_theme
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx artellapipe
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: kbsquQLieTYnXGBkfCsNm3+jal180vUoXb0qR6Pd0fHDN5NzDzuWLovOJB9l00UOijT8ULIQ9OLCDXze7e+O2mie2W+tIQrX1vWKLbpkjgCSUu3O0m839Eq56qhdWx7oOH50/CAzJ96z4ygDM7qCSP44aizK4RH3blHpbW07SiOhDm3MdeB18oxfzCdtg3+cQv3n7GEUJ/j1Ib9MUQoDa7ULL11iy9qItY8Drfa6ymGbUsTRIhP8E7XPTd9aGRzY/C9yKMFvCQqZ7u66ENa67uKmDUhvpBqAAhgv5hlPfJwqQMHSz9a4eNbzdsEovBZPQCguV1rapKVzTmbUBAjmucZg8Mo1oplh8YQ95MmXKGmHe9ZvceLvKNFnXr2IUA75W6YY7gH8Qvn9u/Hqx3XAZojyV4rsoPk/LHVwxjWLdyQbgUkkvx/NzH3adDzBEXeCrYVfTQyf83r1m8MeJ2e3UgtDwPpOWap7iVf05VRBHpmCZxyv7idhLeyi0BT8AYHNq9JYYSrXK0rk5JHsVx/JIP4l1OzbtRCqJe4FUoVe17OoAErJFCi+EY+EU7odbxGF7zelblKcIHAHv0HsKTOdq3LDx5SJ68I4YjiqOjwU+F6xzxnOXwDlUOwSiA/YkWV7IXeVH4lD6OmwE7bgQ0S8gPoyDH+ErJJu45ybpPjeRRE=
    on:
      branch: master
      tags: true